# Notes for Deep Learning by Udacity

## Starting off!

A well conditioned problem makes it easier for the optimiser to do it's job





### Importance of validation / cross-validation sets

Training a classifier is usually trial and error
Classifier has seen the test data. i.e. we have given info about the test set to the classifier. Test data 'bleeds' into your training data. Hence use the cross validation set.
Use the test set to measure the classifiers real performance.

Bigger the validation, more precise the numbers??

For a Validation set of >30,000; improvement of 0.1% in accuracy is considered significant (This is assuming that an improvement of 30 samples is considered significant) assuming classes are balanced.

Cross-validation can be used if the dataset is not large enough to take 30,000 examples into the validation set.


In [1]:
import numpy as np
a = [[[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]],[[7,8,9],[77,88,99]]]
a= np.array(a)
print(a)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]

 [[ 7  8  9]
  [77 88 99]]]


In [2]:
b=np.reshape(a, (a.shape[0], a.shape[1]*a.shape[2]))

In [3]:
print(a.shape[0])
print(b)

3
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]


In [4]:
np.ascontiguousarray(a)

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

In [33]:
c= np.array([12,13, 14])
print(b.shape)
print(c)
# np.concatenate([b,c], axis=1)
# np.hstack((b,c.T))
c = np.reshape(c, (3,1))
np.concatenate([b,c], axis=1)



(3, 6)
[12 13 14]


array([[ 1,  2,  3, 11, 22, 33, 12],
       [ 4,  5,  6, 44, 55, 66, 13],
       [ 7,  8,  9, 77, 88, 99, 14]])

In [17]:
??np.concatenate()

In [43]:
print(a)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]

 [[ 7  8  9]
  [77 88 99]]]


In [35]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 22, 33, 44, 55, 66, 77, 88,
       99])

In [42]:
set(map(tuple,np.reshape(a, (a.shape[0], a.shape[0]*a.shape[1]))))


{(1, 2, 3, 11, 22, 33), (4, 5, 6, 44, 55, 66), (7, 8, 9, 77, 88, 99)}

In [44]:
np.ascontiguousarray(a)

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

In [47]:
a.flatten()

array([ 1,  2,  3, 11, 22, 33,  4,  5,  6, 44, 55, 66,  7,  8,  9, 77, 88,
       99])

In [49]:
np.ravel(a)

array([ 1,  2,  3, 11, 22, 33,  4,  5,  6, 44, 55, 66,  7,  8,  9, 77, 88,
       99])